### ISSUE TITLE
shackle exposed helm buffer to winner-undo

### ISSUE THREAD

**Issue by QiangF** [wasamasa/shackle#37] opened 2016-08-25 00:58 UTC
By default, helm add its buffers to winner-boring-buffers with this hook.

    (add-hook 'helm-cleanup-hook #'helm-handle-winner-boring-buffers)

If I have this rule for helm in shackle:

    (setq shackle-rules
    '( ("\\`\\*helm.*?\\*\\'" :regexp t :align t :ratio 0.4)))

then helm buffers are not exclude from winner undo. You can try it with:

1 some buffer switching in one window layout
2 run helm-M-x
3 some buffer switching in one window layout
4 use winner undo and you will get a two window layout

**Comment by wasamasa** [comment] 2016-08-25 07:24
`helm-handle-winner-boring-buffers` is a curious one, why not just customize `winner-boring-buffers` directly?

**Comment by QiangF** [comment] 2016-08-25 08:14
Removing the hook and set winner-boring-buffers with the list of helm buffer names, I get the same result.

**Comment by QiangF** [comment] 2016-08-25 08:14
Removing the hook and set winner-boring-buffers with the list of helm buffer names, I get the same result.

**Comment by QiangF** [comment] 2016-08-25 08:14
Removing the hook and set winner-boring-buffers with the list of helm buffer names, I get the same result.

**Comment by QiangF** [comment] 2016-08-25 08:14
Removing the hook and set winner-boring-buffers with the list of helm buffer names, I get the same result.

**Comment by QiangF** [comment] 2016-08-25 08:14
Removing the hook and set winner-boring-buffers with the list of helm buffer names, I get the same result.

**Comment by QiangF** [comment] 2016-08-25 08:14
Removing the hook and set winner-boring-buffers with the list of helm buffer names, I get the same result.

**Comment by wasamasa** [comment] 2016-08-25 08:17
I'm having difficulties reproducing this one.  I recall seeing similar symptoms before and did assume helm did *not* integrate with winner-mode at all... It would be great if you could write up an init file that leads to the phenomenon.

**Comment by wasamasa** [comment] 2016-08-25 08:34
Also, now that I think of it, are you possibly on an old version of Shackle?  I used to have an implementation of `:align` there which did save the window configuration and restore it afterwards.  This kind of thing did obviously mess with helm... The new version shouldn't as it merely splits the root window.

**Comment by QiangF** [comment] 2016-08-25 08:49
I am using Version: 0.9.0. If I remove the align keyword, everything is fine. To reproduce the bug, you can try with this init.el file.
;; All packages are the latest from Melpa

    (setq debug-on-error t)
    (setq load-prefer-newer t)
    (require 'package)
    (setq package-enable-at-startup nil
        package-user-dir "~/.emacs.d/elpa/")
    (package-initialize)

    (require 'use-package)
    (setq use-package-verbose t)
    (use-package bind-key
    :ensure t)
    (use-package diminish
    :ensure t)

    (use-package shackle
    :ensure t
    :init
        (shackle-mode)
    :config
        (setq shackle-rules
        '(  ("\\`\\*helm.*?\\*\\'" :regexp t :align t :ratio 0.4)
            (compilation-mode :select t)
            (TeX-errors-mode :select t)
            (append special-buffer-regexp (list :regexp t :select t))
            (help-mode :other t :select t)
            (special-mode :other t :select t))
            shackle-default-rule '(:select t))
    )


    (use-package helm
    :ensure t
    :bind
    (("M-x" . helm-M-x)
        ("C-x b" . helm-mini)
        ("C-x C-f" . helm-find-files))
    :init
        (helm-mode 1)
    )



    (use-package winner
    ; winner-boring-buffers, buffers to exclude in winner-undo
    :bind 
        (("C-9" . winner-redo)
        ("C-8" . winner-undo))
    :init
        (winner-mode)
    :config
    (setq winner-boring-buffers
            '("*Apropos*" "*Buffer List*" "*Completions*" "*Compile-Log*" "*cvs*" "*Fuzzy Completions*"
            "*Help*" "*Ibuffer*" "*inferior-lisp*"
            "*helm mini*" "*helm projectile*" "*helm M-x*" "*helm resume*"))
    )

;; After emacs startup, C-x d jump to a folder, then M-x run
;; helm-M-x, the C-x d jump to another folder, then use c-8
;; winner-undo to get back and you will get a two window layout.

**Comment by wasamasa** [comment] 2016-08-25 16:14
Can't reproduce it with that either.  There must be more to it than this sequence of events.  Can you reproduce it in a minimal Emacs session as started with `emacs -Q`?

**Comment by QiangF** [comment] 2016-08-31 06:29
It can be reproduced with the following steps
1 start emacs -Q
2 create a buffer enter

    (setq load-prefer-newer t)
    (require 'package)
    (setq package-enable-at-startup nil
        package-user-dir "~/.emacs.d/elpa/")
    (package-initialize)

    (require 'shackle)
    (setq shackle-rules
        '(  ("\\`\\*helm.*?\\*\\'" :regexp t :align t :ratio 0.4)
            (compilation-mode :select t)
            (TeX-errors-mode :select t)
            (append special-buffer-regexp (list :regexp t :select t))
            (help-mode :other t :select t)
            (special-mode :other t :select t))
            shackle-default-rule '(:select t))
    (shackle-mode)

    (require 'helm)
    (global-set-key (kbd "M-x")  'helm-M-x)
    (helm-mode 1)

    (require 'winner)
    (global-set-key (kbd "C-9")  'winner-redo)
    (global-set-key (kbd "C-8")  'winner-undo)
    (winner-mode)
    (setq winner-boring-buffers
            '("*Apropos*" "*Buffer List*" "*Completions*" "*Compile-Log*" "*cvs*" "*Fuzzy Completions*"
            "*Help*" "*Ibuffer*" "*inferior-lisp*"
            "*helm mini*" "*helm projectile*" "*helm M-x*" "*helm resume*"))

3 select all and eval-region
4 M-x will show three buffers
5 C-x d to a directory
6 winner undo will show a two window layout.

The problem is gone when shackle is diabled.
emacs 24.5
helm     Version: 20160818.2123
shackle Version: 20160517.1615

**Comment by wasamasa** [comment] 2016-08-31 07:03
Ah, what I was missing is that I needed to undo *twice* to get a two window layout...

**Comment by wasamasa** [comment] 2016-08-31 07:12
This is a duplicate of #28.  Add `(setq helm-display-function 'pop-to-buffer)` to your init file and the bug should go away.

**Closed by wasamasa** 2016-08-31 07:12 UTC
